import React, { useState, useEffect, useRef } from 'react';

const LyricsView = ({ currentSong, currentTime }) => {
    const [lyricsLines, setLyricsLines] = useState([]);
    const [isLoading, setIsLoading] = useState(false);
    const [hasSyncedData, setHasSyncedData] = useState(false);
    const activeLineRef = useRef(null);

    const [lyricsSource, setLyricsSource] = useState(null);

    // Helper: Parse LRC format "[mm:ss.xx] lyrics"
    const parseLrc = (lrcText) => {
        const lines = lrcText.split('\n');
        const parsed = [];
        const timeRegex = /\[(\d{2}):(\d{2})\.(\d{2,3})\]/;

        for (const line of lines) {
            const match = line.match(timeRegex);
            if (match) {
                const minutes = parseInt(match[1]);
                const seconds = parseInt(match[2]);
                const milliseconds = parseInt(match[3].padEnd(3, '0'));
                const time = minutes * 60 + seconds + milliseconds / 1000;
                const text = line.replace(timeRegex, '').trim();
                // Filter out metadata tags like [length:...] if text is empty or starts with title/artist tag in content
                if (text && !text.startsWith('length:')) parsed.push({ time, text });
            } else if (line.trim() && !line.startsWith('[') && !line.endsWith(']')) {
                // Fallback for lines without timestamp in mixed content, but avoid strict metadata
                parsed.push({ time: -1, text: line.trim() });
            }
        }
        return parsed;
    };

    const fetchLyrics = async () => {
        setIsLoading(true);
        setHasSyncedData(false);
        setLyricsLines([]);
        setLyricsSource(null);

        try {
            const { getLyrics } = await import('../api/music');
            const result = await getLyrics(currentSong);

            if (result && result.text) {
                setLyricsSource(result.source); // 'saavn', 'lrclib', 'gemini'
                if (result.type === 'lrc') {
                    const lrcData = parseLrc(result.text);
                    setLyricsLines(lrcData.length > 0 ? lrcData : [{ text: "Lyrics format not supported.", time: -1 }]);
                    setHasSyncedData(lrcData.length > 0);
                } else {
                    const rawLyrics = result.text;
                    const preProcessed = rawLyrics.replace(/<br\s*\/?>/gi, '\n');
                    const cleanText = new DOMParser().parseFromString(preProcessed, "text/html").body.textContent || "";
                    const lines = cleanText.split('\n').map(l => ({ text: l.trim(), time: -1 })).filter(l => l.text);
                    setLyricsLines(lines);
                    setHasSyncedData(false);
                }
            } else {
                setLyricsLines([]);
            }
        } catch (e) {
            console.error("Lyrics fetch failed", e);
            setLyricsLines([]);
        } finally {
            setIsLoading(false);
        }
    };

    // Fetch Lyrics
    useEffect(() => {
        if (!currentSong) return;
        fetchLyrics();
    }, [currentSong]);

    // Active Index Logic
    const getActiveIndex = () => {
        if (!hasSyncedData || !lyricsLines.length) return -1;
        const index = lyricsLines.findIndex(line => line.time > currentTime);
        if (index === 0) return 0;
        if (index === -1) return lyricsLines.length - 1;
        return index - 1;
    };

    const activeIndex = getActiveIndex();

    // Auto-Scroll
    useEffect(() => {
        if (hasSyncedData && activeLineRef.current) {
            activeLineRef.current.scrollIntoView({
                behavior: 'smooth',
                block: 'center',
            });
        }
    }, [activeIndex, hasSyncedData]);

    const getSourceLabel = () => {
        if (!lyricsSource) return "";
        if (lyricsSource === 'saavn') return "Source: JioSaavn (Official)";
        if (lyricsSource === 'lrclib') return "Source: LrcLib (Community)";
        if (lyricsSource === 'gemini') return "✨ Generated by Gemini AI";
        return "";
    };

    return (
        <div className="flex flex-col items-center justify-start h-full overflow-y-auto px-8 py-24 text-center no-scrollbar space-y-6 animate-fade-in w-full max-w-2xl mx-auto scroll-smooth">
            {isLoading ? (
                <div className="flex flex-col items-center justify-center mt-20 space-y-4">
                    <div className="w-8 h-8 border-4 border-green-500 border-t-transparent rounded-full animate-spin"></div>
                    <div className="text-white/50 animate-pulse">Searching Lyrics & Generating via AI...</div>
                    <div className="text-xs text-white/30">(This might take a few seconds)</div>
                </div>
            ) : lyricsLines.length > 0 ? (
                <>
                    {lyricsLines.map((line, i) => {
                        const isActive = i === activeIndex;
                        const isHighlighted = hasSyncedData ? isActive : false;
                        return (
                            <p
                                key={i}
                                ref={isHighlighted ? activeLineRef : null}
                                className={`transition-all duration-500 my-2 cursor-pointer
                            ${hasSyncedData
                                        ? (isHighlighted
                                            ? 'text-2xl md:text-3xl font-bold text-white scale-105 drop-shadow-md py-4'
                                            : 'text-lg md:text-xl text-white/40 hover:text-white/80')
                                        : 'text-lg md:text-2xl font-medium text-white/70 hover:text-white'
                                    }
                        `}
                            >
                                {line.text}
                            </p>
                        )
                    })}
                    {/* Source Indicator */}
                    <div className="mt-8 pt-8 border-t border-white/10 w-full animate-fade-in">
                        <span className={`text-xs font-mono px-3 py-1 rounded-full ${lyricsSource === 'gemini' ? 'bg-purple-500/20 text-purple-200 border border-purple-500/30' : 'bg-white/5 text-white/30'}`}>
                            {getSourceLabel()}
                        </span>
                    </div>
                </>
            ) : (
                <div className="flex flex-col items-center justify-center mt-20 space-y-4">
                    <p className="text-white/50">Lyrics not available for this song.</p>
                    <button
                        onClick={fetchLyrics}
                        className="px-6 py-2 bg-white/10 hover:bg-white/20 text-white rounded-full text-sm font-medium transition active:scale-95"
                    >
                        Retry Search
                    </button>
                    {(currentSong?.hasLyrics === false) && <p className="text-xs text-red-400">Official source says no lyrics.</p>}
                </div>
            )}
            <div className="h-48"></div>
        </div>
    );
};

export default LyricsView;
